name: ci

on:
  push:
    paths:
      - Dockerfile
      - Run.R
  repository_dispatch: 
    types:
      - build 

jobs:
  r-cmd-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SeaSondeR repository
        uses: actions/checkout@v3
        with:
          repository: GOFUVI/SeaSondeR 
          path: SeaSondeR

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("devtools", "rcmdcheck"))'
          Rscript -e 'devtools::install_deps("SeaSondeR", dependencies = TRUE)'

      - name: Run R CMD check
        run: |
          Rscript -e 'rcmdcheck::rcmdcheck("SeaSondeR", error_on = "error")'

  docker:
    needs: r-cmd-check
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gofuvi/seasonder-rest:latest