name: Trigger Dispatch

on:
  push:
    branches:
      - main

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/GOFUVI/seasonder-rest/dispatches \
          -d '{"event_type": "seasonder-main-push"}'